#!/bin/bash
#launch LEMP
#1. create catalog tree
#2. create file docker-compose.yml
#3. input NGINX ip address in file hosts of host.loc

#1. create catalog tree
mkdir -p logs nginx public
touch logs/nginx-{access,error}.log

#create file LEMP/nginx/default
cp -f default /etc/nginx/

#create file LEMP/public/index.php
cp -f index.php public/

#2. create file docker-compose.yml

#run docker
docker-compose up -d

#3. input NGINX ip address in file hosts of host.loc

sed -i '/host.loc/d' /etc/hosts
var=`docker ps | grep nginx | awk '{print $1}' | xargs docker inspect --format '{{ .NetworkSettings.IPAddress }}'`
sudo cat > /etc/hosts << EOF
$var host.loc
EOF

